### ISSUE TITLE
chatGLM2模型转换之后，运行报错

### ISSUE THREAD

**Issue by mocushile-gif** [ztxz16/fastllm#149]
model = llm.from_hf(model, tokenizer, dtype = "float16")
response = model.response("你好")
print(response)
---------------------------------------------------
报错信息如下：
convert ( 200 / 200 )
Warmup...
status = 13
1 16 128
Error: cublas error.
terminate called after throwing an instance of 'char const*'
-----------------------------------------------------
版本信息：
torch:1.10.2
nvcc --version:11.4
transformers:4.30.2
cmake:3.14.4
Ubuntu 20.04.2

**Comment by zyt1024** [comment]
`Error: cublas error.` 我也碰到了这个错误，大哥解决了嘛

**Comment by mocushile-gif** [comment]
> 

目前还没有，我准备将gcc版本和cmake版本进行升级之后 重新测试一下。

**Comment by zyt1024** [comment]
我的已经解决了，我的是只出现了这一处错误：
``` bash
用户：hello

ChatGLM：Error: cublas error.

```
**出错原因**是显存爆了，才出现的这个错误的

**Comment by frankxyy** [comment]
同遇到这个问题，转换的模型是llama-7b。rtx3090上出现，a100上转换正常。排查不是显存爆

**Comment by mocushile-gif** [comment]
> 

请问你使用的是多大的内存，我是在T4卡上跑的，只有16GB显存

**Comment by zyt1024** [comment]
> 同遇到类似的问题，不过我是chatglm2-6b可以跑，但llama-7b float32至float16 quant转换报错。llama报错在rtx3090上出现，a100上则转换正常。排查确实是显存爆了，不过为啥7b的模型quant时需要超过24G的显存。。

这个问题可以看看这个issue:[chatglm2-6b使用fastllm疑问 #153
](https://github.com/ztxz16/fastllm/issues/153), 如果直接加载转换后的模型，占用显存就会少了，如果先加载原先的模型，然后转换，则会占用很多显存，因为原来的模型也占用了显存。

**Comment by frankxyy** [comment]
@zyt1024 了解了，话说fp16 quant能否不通过 ./quant 命令来转，而是直接export呢？

**Comment by zyt1024** [comment]
> @zyt1024 了解了，话说fp16 quant能否不通过 ./quant 命令来转，而是直接export呢？
这个没有试过哎，大佬可以试一试，可以的话，也可以分享分享
