### ISSUE TITLE
Error: CUDA error when release memory! state 4.

### ISSUE THREAD

**Issue by htsun1998** [ztxz16/fastllm#363]
# 使用转换后的baichuan2的flm模型进行推理后报错
报错：Error: CUDA error when release memory! state 4.

**模型转换代码**
```python
import sys
import torch
from transformers import AutoModelForCausalLM, AutoTokenizer
from transformers.generation.utils import GenerationConfig
from fastllm_pytools import torch2flm

if __name__ == "__main__":
    modelpath = "/data/models/Baichuan2-13b-chat"
    tokenizer = AutoTokenizer.from_pretrained(modelpath, use_fast=False, trust_remote_code=True)
    model = AutoModelForCausalLM.from_pretrained(modelpath, device_map="auto", torch_dtype=torch.float32, trust_remote_code=True)

    # normalize lm_head
    state_dict = model.state_dict()
    state_dict['lm_head.weight'] = torch.nn.functional.normalize(state_dict['lm_head.weight'])
    model.load_state_dict(state_dict)

    try:
        model.generation_config = GenerationConfig.from_pretrained(modelpath)
    except:
        pass

    dtype = sys.argv[2] if len(sys.argv) >= 3 else "float16"
    exportPath = sys.argv[1] if len(sys.argv) >= 2 else "baichuan2-7b-" + dtype + ".flm"
    torch2flm.tofile(exportPath, model.to('cpu'), tokenizer, dtype=dtype)
```
**推理代码**
```python
from fastllm_pytools import llm
model = llm.model("/data/models/baichuan2-13b-fp16.flm")

# 生成回复
print(model.response("晚上睡不着怎么办？"))

# 流式生成回复
for response in model.response("你好"):
    print(response, flush = True, end = "")
```
**报错详情**
<img width="568" alt="image" src="https://github.com/ztxz16/fastllm/assets/96409687/0bb6fad4-eb32-44f9-acdf-4f5aa017f579">

**Comment by TylunasLi** [comment]
应该是在退出的时候报错的，state是CudaError_t的下标。
根据文档：

> cudaErrorCudartUnloading = 4
> 这表明无法执行CUDA运行时API调用，因为它是在进程关闭期间（在卸载CUDA驱动程序后的某个时间）调用的。

意味着系统先卸载了CUDA驱动程序，再释放模型所占的显存。
如果不影响程序执行，可以尝试退出前先执行
model.release_memory()。

**Comment by htsun1998** [comment]
谢谢，已解决
