### ISSUE TITLE
[不完全可用]项目在 P102-100 (Pascal SM 6.1) 上的运行方法-直接看最底下

### ISSUE THREAD

**Issue by 2794054779** [ztxz16/fastllm#679]
一、前言：
        目前我主要用windows、wsl2。我一开始在conda里直接安装了ftllm，运行模型的时使用p102提示flashinfer不支持，使用cpu则直接维度错误，加fp32参数也没用（？），遂企图改代码编译，在windows下编译较为困难，转入wsl2中的Ubuntu 24.04编译，目前main能够编译、运行，但是打包成py库之后遇到一堆问题难以解决（超出知识界限了QWQ）。在此上传我的日志，希望大佬指点，也为后来的pascal架构的开发者们提供点参考。

二、环境：

### 1. WSL2 状态 (从 Windows 视角) ###
env_info.sh: line 11: wsl: command not found

### 2. Ubuntu 发行版与内核 ###
Description:    Ubuntu 24.04.3 LTS
Release:        24.04
Linux localhost 6.6.87.2-microsoft-standard-WSL2 #1 SMP PREEMPT_DYNAMIC Thu Jun  5 18:30:46 UTC 2025 x86_64 x86_64 x86_64 GNU/Linux

### 3. CPU 架构与虚拟化支持 ###
Architecture:                         x86_64
CPU(s):                               6
On-line CPU(s) list:                  0-5
Model name:                           AMD Ryzen 7 6800H with Radeon Graphics
Thread(s) per core:                   2
Core(s) per socket:                   3
Socket(s):                            1
NUMA node0 CPU(s):                    0-5

虚拟化支持 (vmx/svm):
6

### 4. 内存使用情况 ###
               total        used        free      shared  buff/cache   available
Mem:           5.8Gi       1.3Gi       3.9Gi       5.6Mi       821Mi       4.5Gi
Swap:          2.0Gi          0B       2.0Gi

### 5. 编译器版本 ###
gcc (Ubuntu 13.3.0-6ubuntu2~24.04.1) 13.3.0

g++ (Ubuntu 13.3.0-6ubuntu2~24.04.1) 13.3.0

### 6. CUDA 相关信息 ###
Cuda compilation tools, release 12.6, V12.6.20
name: driver_version: compute_cap
NVIDIA P102-100: 582.08: 6.1

### 7. Python 环境 ###
Python 3.12.3
ftllm                    0.1.6.4

### 8. 关键环境变量 ###
CUDA_HOME:
PATH (CUDA相关):
/usr/local/cuda-12.6/bin
/mnt/d/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v12.8/bin
/mnt/d/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v12.8/libnvvp
/mnt/d/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v11.8/bin
/mnt/d/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v11.8/libnvvp
/mnt/d/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v12.8/bin

### 9. 磁盘空间 ###
Filesystem      Size  Used Avail Use% Mounted on
/dev/sdf       1007G   19G  937G   2% /
C:\             120G  120G   80M 100% /mnt/c

### 10.使用的模型 ###
https://huggingface.co/Qwen/Qwen3-0.6B

三、日志总结（DS总结）：

### 整体概述

在尝试将 fastllm 适配到 **P102-100 (GP102, Compute Capability 6.1)** 显卡时，遇到了一系列编译期和运行期的问题。该显卡不支持 Tensor Core（需要 SM 7.0+），也不支持 BF16（需要 SM 8.0+），仅支持 FP16（2x FP32 吞吐）。项目主要针对 SM 70+ 开发，因此在 SM 61 上暴露了多个兼容性缺陷。

主要困难集中在：
1. **FlashInfer 依赖 CUDA 同步原语**（`cuda::barrier`），仅 SM 70+ 支持
2. **NVCC + GCC 13 + AMX 指令集冲突**，导致系统头文件被错误包含
3. **CUDA CUB 头文件缺失**（因条件编译跳过 flashinfer 后间接依赖丢失）
4. **Python 绑定的运行时设备调度不一致**，导致 Embedding 层 `memcpy` 段错误
5. **`ToDataTypeForceCPU` 将 Embedding weight 原地转换为 FP16** 后引发内存访问错误
6. **多轮推理中 weight 在 CPU/CUDA 间迁移**，`cpuData` 被释放后再次访问导致崩溃

以下按时间顺序详细记录。

---

#### 1. 项目初览 & 编译配置准备（2026-xx-xx）

- **目标**：在 P102-100 上编译 fastllm，启用 CUDA 但禁用 Tensor Core。
- **建议编译命令**：
  ```bash
  bash install.sh -DUSE_CUDA=ON -DCUDA_ARCH=61 -DCUDA_NO_TENSOR_CORE=ON
  ```

#### 2. 首次编译报错（2026-05-18）

**错误 A**：FlashInfer 的 `<cuda/std/barrier>` 不兼容 SM < 70  
```
error: #error "CUDA synchronization primitives are only supported for sm_70 and up."
```
**错误 B**：AMX 内建函数未定义（`__builtin_ia32_ldtilecfg` 等）  
来自 GCC 13 的 `amxtileintrin.h`，在 NVCC 编译 host 代码时被包含。
**错误 C**：`FastllmAddToKernel` 未声明  
`fastllm-linear-fp16.cu` 调用了该 kernel 但头文件中缺少 `extern __global__` 声明。

#### 3. 解决方案设计与实施（2026-05-18）

- **针对 FlashInfer**：在 `fastllm-attention.cu` 及相关文件中，用条件编译包裹所有 flashinfer 头文件和调用：
  ```cpp
  #if !defined(__CUDA_ARCH__) || __CUDA_ARCH__ >= 700
  // flashinfer 相关代码
  #endif
  ```
- **针对 AMX**：尝试多种方法（修改 `CMakeLists.txt` 的 `-march=native` → `-march=x86-64-v3`，传递 `-Xcompiler=-mno-amx-tile` 等）均无效，最终直接修改系统头文件 `/usr/include/x86_64-linux-gnu/gcc/13/immintrin.h`，为 AMX 头文件添加 `#ifndef __CUDACC__` 保护。
- **针对未声明 kernel**：在 `include/devices/cuda/fastllm-cuda.cuh` 中补充 `extern __global__ void FastllmAddToKernel(...);`。

#### 4. 新错误：CUB 头文件缺失（2026-05-18）

由于 `sampling.cuh`（flashinfer）被条件编译跳过，`cub/cub.cuh` 不再被间接包含，导致 `BlockReduce` 等未定义。  
**修复**：在 `fastllm-cuda.cu` 中显式 `#include <cub/cub.cuh>` 并添加 `using MaxReduceOp = cub::Max;`。

#### 5. NCCL 头文件缺失（2026-05-18）

`fastllm-multicuda.cu` 需要 `nccl.h`。  
**修复**：安装 `libnccl-dev`。

编译通过 ✅

#### 6. 运行时错误：FlashInfer invalid device function（2026-05-18）

虽然条件编译避免了 kernel 编译，但 host 代码仍会调用 flashinfer API，在 SM 61 上尝试 launch kernel 时报错。  
**修复**：在 `FastllmCudaHalfPagedAttention` 等函数入口添加运行时检查：
```cpp
if (!getCudaInfos()->hasTensorCore) { return false; }
```

#### 7. Python 绑定运行时段错误（2026-05-18 → 2026-05-19）

**现象**：编译安装后，`ftllm run model.flm` 在推理时 `Segmentation fault`。但 C++ 原生可执行文件 `build/main -p model.flm` 正常推理。

**排查过程**：
- 确认 `.so` 文件一致，打包无误。
- GDB 显示段错误在 `CpuEmbeddingDirect::Run` 中的 `memcpy`，源地址无效（`rsi` 不可访问）。
- 对比 `build/main` 和 `ftllm run` 的代码路径，发现两者都走 `CreateLLMModelFromFile`，但 `Embedding` 调用方式不同：
  - `build/main` 使用全局函数 `Embedding()` → `Executor::Run("Embedding")` → `CpuEmbedding::Run`（不修改 weight）
  - `ftllm run` 在 `ForwardV2` 中使用 `EmbeddingBlock` → 会调用 `ToDataTypeForceCPU(*weight, outputType)`，将 weight 从 FP32 原地转换为 FP16。

**根本原因定位**：
- `ToDataTypeForceCPU` 内部调用 `CpuToFloat16::Run`，该操作会 `delete[]` 旧的 FP32 `cpuData`，再 `new uint8_t[newBytes]` 分配 FP16 内存。后续 `CpuEmbeddingDirect::Run` 虽然用 `unitSize` 计算偏移，但实际访问新内存时发生段错误（可能因内存分配失败或对齐问题）。
- **禁用 `ToDataTypeForceCPU` 后**，第一轮推理成功输出 `AI:`，证明问题确由该转换引起。
- 进一步发现：第一轮推理中，某些 Linear 等 op 被 dispatch 到 CUDA device，触发 `ToDevice(CPU→CUDA)`，由于 `isModelWeight=1`，`cpuData` 被释放（`delete[]`）。第二轮推理时，`EmbeddingBlock` 发现 `dataDevice=CUDA` 而 `cpuData=nullptr`，调用 `ToDevice(CPU)` 试图从 GPU 迁回数据。虽然迁回逻辑本身正确，但后续 `EmbeddingDirect` 仍然崩溃（可能是多线程竞态或内存状态不一致）。

#### 8. 最终修复方案及遗留问题

**已实施修复**：
- 在 `embeddingblock.cpp` 中：
  1. 增强 `weight->ToDevice(CPU)` 前的检查：若 `dataDevice=CUDA` 但 `cudaData==nullptr`，直接重建 `cpuData` 而不执行 `cudaMemcpy`。
  2. 将 `ToDataTypeForceCPU` 的目标类型改为 `FLOAT32`（而非 `outputType` 的 FP16），避免 FP16 转换带来的内存问题。
- 同时强制将 weight 转为 FP32，解决 `--device cpu` 路径下的类型不匹配问题。

**测试结果**：
- 默认参数运行：第一轮推理成功输出 `AI:`，但第二轮推理或退出时仍有段错误（源于 weight 在 CPU/CUDA 间迁移后的状态不一致）。
- `--device cpu` 运行：因类型转换已修复，不再报错，但推理卡死（全部 op 走 CPU 性能极低）。

**结论**：
- **编译问题已全部解决**（FlashInfer 条件编译、AMX 头文件冲突、CUB/NCCL 依赖）。
- **运行时问题**：Python 绑定在混合设备调度（Embedding 强制 CPU，Linear 自动 CUDA）时，`embed_tokens.weight` 的 `cpuData` 生命周期管理存在缺陷，导致多轮推理崩溃。C++ 原生程序 `build/main` 可稳定运行，但无法替代 `ftllm` 的全部功能（如 HF 自动下载、server、webui）。

### 建议项目改进方向

1. **为 SM < 70 完全禁用 FlashInfer**：除了条件编译，还应在 CMake 层面提供选项，避免引入 flashinfer 依赖。
2. **修复 `CpuToFloat16::Run` 中的内存分配/释放逻辑**，确保转换后的 `cpuData` 可被 `CpuEmbeddingDirect` 正确读取。
3. **统一 Embedding weight 的设备策略**：对于 `GetCudaEmbedding()=false` 的情况，应阻止任何 op 将该 weight 迁移到 CUDA，或至少在 `Data::ToDevice` 中为 Embedding weight 保留 `cpuData` 副本。
4. **Python 绑定初始化时提供更明确的设备控制**，允许用户强制所有 op 使用 CPU，避免自动 CUDA 调度带来的复杂状态管理。

---

以上为本次适配 P102-100 过程中遇到的主要困难及解决尝试，供项目开发者参考。如有进一步信息或补丁，欢迎讨论。

详细日志如下：

[排错日志.md](https://github.com/user-attachments/files/28020807/default.md)
（日志与最终解法相去甚远......可能没什么用）

**Comment by 2794054779** [comment]
今天进行了排错，一次在前移到5.18的版本的时候，修改attention的时候出了奇奇怪怪的格式bug，找了半天放弃了，重新弄了一份；此外，在-DPY_API=ON/OFF的时候，也晕了一大圈。目前暂时可以正常跑小模型了，例如Qwen3-0.6B。粗略总结的排错日志如下（ai生成）：


## 进展更新（2026-05-21）

### 当前环境
- 硬件：P102-100 (Pascal SM 6.1, 10GB)
- 系统：WSL2 Ubuntu 24.04, GCC 13.3, CUDA 13.0 (驱动 580.118)
- fastllm 版本：5.18 (commit 219579a1)

### 已解决：纯 CPU 编译与测试
- `build/main` 可正常推理（HF 目录和 `.flm` 均通过）
- Python 绑定 `ftllm run` 在默认参数下因 **新引擎 (ForwardV2) 的 AddTo 类型检查** 失败：
  ```
  input0.type=0(FLOAT32) input1.type=7(FLOAT16)
  ```
  原因是 `.flm` 文件中部分 weight 为 FP16、部分为 FP32，混合使用时 `AddTo` 报错。

### 解决方案（临时绕过）
设置两个环境变量即可让 `ftllm run` 正常工作：
```bash
USE_OLD_ENGINE=1 FASTLLM_SKIP_WARMUP=1 ftllm run /path/to/model --device cpu
```
已验证对 Qwen3-0.6B 有效，推理正常输出。

**原理**：
- `USE_OLD_ENGINE=1` → 强制 `Response()` 走旧引擎 `ForwardBatch()`（无 AddTo 类型检查）
- `FASTLLM_SKIP_WARMUP=1` → 跳过 `AutoWarmup()`（避免 warmup 中触发 ForwardV2 报错）

### CUDA 编译适配（SM 61）已完成
针对 P102-100 的 FlashInfer、CUB 等问题，做了完整的条件编译修改（详见日志中修改清单 ①~⑩）。编译通过，无 error。
但是昨天的AMX问题没有复现...

### 两种 Python 绑定模式说明
| 模式 | 编译选项 | 生成产物 | 入口 |
|------|----------|----------|------|
| `PY_API=OFF`（默认） | 无 | `libfastllm_tools.so` + `ftllm` 命令行 | `ftllm run` |
| `PY_API=ON` | `-DPY_API=ON` | `pyfastllm.cpython-*.so` | `import pyfastllm` |

当前 `install.sh` 使用默认模式，因此 `ftllm run` 可正常使用；`PY_API=ON` 模式仅供直接 import 使用。

### 当前状态总结
- ✅ `build/main` 推理完全正常
- ✅ 通过环境变量，`ftllm run --device cpu` 可正常使用
- ❌ `ftllm run` 默认参数（无环境变量、自动选择 device）因新引擎类型检查仍失败
- ❌ CUDA 模式下尚未完全稳定（多轮推理仍有潜在问题，建议先用 CPU 模式）

下一步建议：**在 Python 绑定层永久启用旧引擎 + 跳过 warmup**，彻底解决 CPU 推理的类型兼容问题。
==========================

[排错日志-5.18-新.md](https://github.com/user-attachments/files/28067556/-5.18-.md)

**Comment by 2794054779** [comment]
起因：直接运行pip的包会报fleshifer错误
方法：排除fleshinfer：
## 修改汇总

| 编号 | 文件 | 修改内容 | 类型 |
|:----:|:----|:--------|:----:|
| ① | `include/devices/cuda/fastllm-cuda.cuh` | 补充 `extern __global__ void FastllmAddToKernel` | 编译期 |
| ② | `src/devices/cuda/fastllm-cuda.cu` | 新增 `#include <cub/cub.cuh>` 和 `using MaxReduceOp` | 编译期 |
| ③ | `src/devices/cuda/fastllm-cuda.cu` | `TopKTopPSampling` 中 FlashInfer 调用加条件编译 | 编译+运行时 |
| ④ | `src/devices/cuda/attention/fastllm-attention.cu` | 顶部 6 个 FlashInfer include 加条件编译 | 编译期 |
| ⑤ | `src/devices/cuda/attention/fastllm-attention.cu` | `FastllmCudaHalfAttention` 重构 | 编译期 |
| ⑥ | `src/devices/cuda/attention/fastllm-attention.cu` | `FastllmCudaHalfPagedAttention` 条件编译 | 编译期 |
| ⑦ | `src/devices/cuda/attention/fastllm-attention.cu` | `FastllmCudaHalfPagedAttentionBatch` 条件编译 | 编译期 |
| ⑧ | `src/devices/cuda/attention/fastllm-attention.cu` | `FastllmCudaMLAPaged` 条件编译 | 编译期 |
| ⑨ | `tools/ftllm/util.py` | 强制 `USE_OLD_ENGINE=1` + `FASTLLM_SKIP_WARMUP=1` | 运行时或编译期 |


注：昨天编译的时候遇到的AMX等错误未遇到，故不修改。

详见

[修改草案v4.md](https://github.com/user-attachments/files/28067490/v4.md)

**Comment by 2794054779** [comment]
并非可用。moe大点的还是会崩

**Comment by 2794054779** [comment]
疑似是因为用的千问3.6，看日志好像不支持

**Comment by TylunasLi** [comment]
感谢测试和反馈
v0.1.5.1 版本，基于[TylunasLi::develop](https://github.com/TylunasLi/fastllm/tree/develop)，可以在sm6.1上使用（建议打开`CUDA_NO_TENSOR_CORE`编译选项），如果仅是Qwen3架构完全可以支持。
v0.1.6.0 后，项目增加了flashinfer依赖，没有再做sm6.1的适配。我可以尝试按照上述思路适配。

**Comment by 2794054779** [comment]
非常感谢您对 fastllm 项目以及 DiskMoE 功能 的持续贡献！我在尝试使用 DiskMoE 时虽然最终效果不太理想（可能受限于我的硬件或模型类型），但依然很佩服这个设计的思路和实现。

**Comment by 2794054779** [comment]
总结：对于帕斯卡架构的卡，只建议在自己去除flashinfer后运行小模型。

在我当前系统下，受限于系统性能，只能推测出cpu+diskmoe是可行的。

对于cuda+diskmoe，会遇到类似如下的报错(原版HF模型或用export导出后的float16模型)：

Error: CUDA error when copy on GPU!

  CUDA error = 1, cudaErrorInvalidValue at /mnt/i/fastllm/6/fastllm/src/devices/cuda/fastllm-cuda.cu:2239

  'invalid argument'

Error: CUDA error when copy on GPU!

  CUDA error = 1, cudaErrorInvalidValue at /mnt/i/fastllm/6/fastllm/src/devices/cuda/fastllm-cuda.cu:2239

  'invalid argument'
据DS分析，有如下结论：

问题 2：Disk MoE + CUDA 的 cudaMemcpyDeviceToDevice 崩溃
          （仓库原生 bug，也是卡住的核心问题）
症状：
  加载成功（Load 0~100% 正常）
  Disk MoE 日志正确输出（SetDiskWeightMeta + Merge2/3: disk）
  推理时大量报错(已跳过warmup)：
    Error: CUDA error when copy on GPU!
    CUDA error = 1, cudaErrorInvalidValue at fastllm-cuda.cu:2239
  --dtype float16 也无法绕开

根因（代码级）：
  1.  Disk MoE 权重的 ResetDiskWeightMeta() 将 expansionBytes = 0
  2.  推理时，MergeMOEBlock 内部触发 Data::CopyFrom()
  3.  CopyFrom 中直接执行：
        FastllmCudaCopyFromDeviceToDevice(this->cudaData, ori.cudaData, GetBytes())
  4.  disk 权重没有 cudaData（nullptr），GetBytes() 也可能返回异常值
  5.  cudaMemcpy(nullptr, nullptr, size, cudaMemcpyDeviceToDevice) → invalid argument

根因总结：
  仓库中 Disk MoE 的实现只考虑了从 CPU 路径跑（--device cpu），
  没有处理 CUDA 路径的 Data::CopyFrom / ToDevice 中对 disk 权重的特殊判断。
  Disk 权重只有文件偏移（diskWeightParts），没有 CPU/GPU 内存指针，
  但 CUDA dispatch 时 CopyFrom 直接拿 nullptr 去拷贝。

无法绕开的原因：
  --dtype float16 只在加载 HF 权重时转成 FP16，
  但 Disk MoE 模式下权重的 core Data 结构（expansionBytes）已经被设为 0，
  后续的 CUDA copy 不管数据是什么类型都会崩。



对此问题，也不排除是我的系统或硬件环境存在特殊性。欢迎遇到类似问题的开发者一起交流、共同排查。
